#!/bin/env python3

# This script adds a header to ASM files before
# assembling them with armips. This is required
# for how patches will be handling region differences.

from jinja2 import Environment,FileSystemLoader
import sys
import os

env = Environment(loader=FileSystemLoader(os.path.dirname(__file__)), trim_blocks=True, lstrip_blocks=True)
header = env.get_template('templates/asm_header.jinja2')
region = sys.argv[3]

with open(sys.argv[2], 'w') as asmFile:
    asmFile.write('; This file is generated by headerize_asm.py.\n')
    asmFile.write(header.render(region=region))
    asmFile.write('\n')
    with open(sys.argv[1], 'r') as asmSourceFile:
        for line in asmSourceFile:
            asmFile.write(line)
    